- name: Update packages
  apt:
    update_cache: yes
  become: yes

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
  - git
  - docker.io
  - default-jre
